# Generated by Django 4.2.11 on 2024-04-20 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('priority', models.CharField(choices=[('Lowest', 'Lowest'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Highest', 'Highest')], default='Lowest', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('OP', 'Open'), ('IN', 'In Progress'), ('CL', 'Closed')], default='OP', max_length=2, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
